apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user
  labels:
    app: user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: udagram-api-user
          image: ambience/udagram-api-user:user-v2
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "200m"
            limits:
              cpu: "500m"
          ports:
            - containerPort: 80
          env:
            - name: URL
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: URL
            - name: AWS_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: AWS_BUCKET
            - name: AWS_PROFILE
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: AWS_PROFILE
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: AWS_REGION
            - name: JWT_SECRET
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: JWT_SECRET
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: POSTGRES_DB
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: POSTGRES_HOST
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: POSTGRES_USERNAME
