apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-frontend
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: udagram-frontend
          image: ambience/udagram-frontend:frontend-v2
          resources:
            requests:
              cpu: "200m"
            limits:
              cpu: "500m"
          ports:
            - containerPort: 80
